# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b84a5eb257f68f245b187d96e900a32c5410e906814b5cff079ce70ce4eddfb414af279f341902185ffb9d2632a0d7756ba213ee7eef829c73213be1458f586f

test:
  secret_key_base: b9b0293623d372449e6d700cf2034db6a8f6a07c9e27dff1d8db027f1c74c78eff549e4f8262213aaf6ada27a76dbaf19da6bd93f824c056fe9c6de751016cb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
